[package]
name = "zellij-cb"
version = "0.1.0"
authors = ["Nuno David <email@ndavd.com>"]
edition = "2021"
license = "MIT"

[dependencies]
colored = "2"
ansi_term = "0.12"
unicode-width = "0.1.8"
zellij-tile = "0.40.1"
zellij-tile-utils = "0.40.1"
